version: '3.8'

services:
  backend:
    build: ./backend
    container_name: villages_conditions_backend
    restart: unless-stopped
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001
    environment:
      # These will be read from the .env file created by GitHub Actions on the server
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL}
      - FIREBASE_ADMIN_SDK_JSON_CONTENT=${FIREBASE_ADMIN_SDK_JSON_CONTENT}
    networks:
      - villages-net

  frontend:
    build:
      context: ./frontend
      args:
        # Pass the API URL during build (fetched from Vault in GitHub Actions)
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: villages_conditions_frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Nginx)
    depends_on:
      - backend # Optional: wait for backend (doesn't guarantee readiness)
    networks:
      - villages-net

networks:
  villages-net:
    driver: bridge