version: '3.8'

services:
  backend:
    build: ./backend
    container_name: villages_conditions_backend
    restart: unless-stopped
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001
    environment:
      # These will be read from the .env file created by GitHub Actions on the server
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL}
      - FIREBASE_ADMIN_SDK_JSON_CONTENT=${FIREBASE_ADMIN_SDK_JSON_CONTENT}
    networks:
      - villages-net

#   frontend:
#     build: ./frontend
#     container_name: villages_conditions_frontend
#     restart: unless-stopped
#     ports:
#       - "8081:80"
#     environment:
#       - VITE_API_BASE_URL=${VITE_API_BASE_URL}
#       - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
#       - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
#       - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
#       - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
#       - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
#       - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
#       - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
#     depends_on:
#       - backend # Optional: wait for backend (doesn't guarantee readiness)
#     networks:
#       - villages-net

# networks:
#   villages-net:
#     driver: bridge




  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
    container_name: villages_conditions_frontend
    restart: unless-stopped
    ports:
      - "8081:80" # Map host port 8080 to container port 80 (Nginx)
    depends_on:
      - backend # Optional: wait for backend (doesn't guarantee readiness)
    networks:
      - villages-net

networks:
  villages-net:
    driver: bridge